### PR TITLE
PLAT-8208: Remove Rancher

### PR DESCRIPTION
**Pull request by mdesantis**
https://wahanda.atlassian.net/browse/PLAT-8208

Remove Rancher logic as Rancher is not used anymore and other updates and fixes (mostly dependencies updates and linting).

### CODE REVIEW

**Review by absinthetized — APPROVED** [review]
not a ruby dev here but seems ok

**Comment by mdesantis** [comment]
> not a ruby dev here but seems ok. I don't know if you want some ruby dev to double check the logic

Nah, I just removed stuff, we just need to test it.

**Comment by mdesantis** [comment]
I changed my idea actually, I noticed that `cdk8s-deployer` mentions `projectId` within code that doesn't seem to be necessarily related to Rancher, so it's probably better to proceed iteratively.

**Comment by absinthetized** [comment]
in this case feel free to merge and "deploy". it's fine for me, but remember to open a followup.

**Pull request merged**
